name: "OwnCloud"
description: "OwnCloud"
version: "0.0.10"
slug: "owncloud"
init: false
advanced: true
map:
  - ssl
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
schema:
  localHost: str
  logLevel: list(off|critical|error|warning|notice|info|debug|trace|all)?
options:
  localHost: "homeassistant.local"
