name: "OwnCloud"
description: "OwnCloud"
version: "0.0.20"
slug: "owncloud"
init: false
advanced: true
map:
  - ssl
ports:
  443/tcp: 8081
  80/tcp: 8082
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
schema:
  localHost: str
  logLevel: list(off|critical|error|warning|notice|info|debug|trace|all)?
options:
  localHost: "homeassistant.local"
